---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: {{ .Values.ui.image }}
        ports:
        - containerPort: {{ .Values.ui.port }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: {{ .Values.ui.env.REACT_APP_BACKEND_URL }}

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.ui.port }}
    targetPort: {{ .Values.ui.port }}
    nodePort: {{ .Values.ui.nodePort }}
  selector:
    app: ui
